### ISSUE TITLE
--test flag or similar for when using test.pypi.org/simple

### ISSUE THREAD

**Issue by sam0jones0** [ddelange/pipgrip#53]
#### Description

Include a --test flag to first search https://test.pypi.org/simple/ for the specified packages before moving on to https://pypi.org/simple to gather the test packages requirements 

#### Use case / motivation

Many users will be testing packages and trying to resolve dependency conflicts before publishing on pypi proper. Initially, I used `pipgrip -v --tree --index-url https://test.pypi.org/simple/ foo` which resulted in "ERROR: No matching distribution found for foo>5.1".

The solution was to run the command `pipgrip -v --tree --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple foo`.

If adding a --test flag is not viable, perhaps adding a short sentence to the help text of --extra-index-url specifying this use case could be beneficial. I would be happy to submit a pull request if you think this is worth doing.

#### Related Issues

No.

----
Great tool, thanks!

**Comment by ddelange** [comment]
Hi @sam0jones0,

Quoting [pip docs](https://pip.pypa.io/en/stable/cli/pip_install/#finding-packages):
> There is no ordering in the locations that are searched. Rather they are all checked, and the “best” match for the requirements (in terms of version number - see PEP 440 for details) is selected.

This means you can simply let index-url default to the official registry, and let pip additionally search test pypi using the extra-index-url.

In general, pipgrip does not interfere with environment variables (allows pip to pick them up as documented by pip),  so in your testing environment you could export `PIP_EXTRA_INDEX_URL=https://test.pypi.org/simple/` which should yield the same results as passing the indices via CLI args.

In light of this, I would argue that the [docs](https://packaging.python.org/guides/using-testpypi/) on TestPyPI are sufficient to guide the user to a workable solution and don't need extra clarification in the pipgrip help text.

Hope that clarifies!
