### ISSUE TITLE
Package Documentation

### ISSUE THREAD

**Issue by pyrodie18** [ddelange/pipgrip#64]
Is there any documentation available to use this as a module within another project?

**Comment by ddelange** [comment]
Hi @pyrodie18,

Currently, [similar](https://github.com/pypa/pip/issues/3121) to pip, the only supported way to invoke pipgrip is via CLI.

For programmatic use, you could try something like:

```py
import json
from pipgrip.pipper import stream_bash_command  # or any alternative

output = stream_bash_command(['pipgrip', '--tree', '--json', '-r', 'reqs.txt'])
deptree = json.loads(output)
```

There are a few other json serialized formats available and documented under `--json`.

Hope that helps!

**Comment by ddelange** [comment]
For future readers, here's a neat wrapper to access binaries available in your PATH: https://github.com/amoffat/sh
