### ISSUE TITLE
Show partial tree on errors

### ISSUE THREAD

**Issue by abitrolly** [ddelange/pipgrip#65]
Need `pipgrip` to render partial tree when installation fails with errors. 

#### Use case / motivation

I need to see who pulls in broken dependency when CI jobs fail.

#### Related Issues

The discussion started here https://github.com/ddelange/pipgrip/issues/52#issuecomment-794050929

And the solution I used was to pipe `requirements.txt` line by line until `pipgrip` fails.
```
cat requirements.txt | xargs -n 1 pipgrip --tree -v
```
However, for [this failure](https://github.com/kvesteri/sqlalchemy-utils/runs/3878543792) the dependencies are specified as `.[test_all]` in `tox.ini` and configured dynamically in `setup.py`.

The `cat` also won't work well for deeper levels in hierarchy.

**Comment by abitrolly** [comment]
The failure happens in `VersionSolver.solve()` even before the dependency tree is built.

https://github.com/ddelange/pipgrip/blob/43405b2849db552da49df3cb50564370eb66590a/src/pipgrip/cli.py#L426

**Comment by ddelange** [comment]
Hi @abitrolly, could you give #67 a spin? If that does the trick for you, I'd merge and release :)

**Comment by ddelange** [comment]
^ see new visualisation @ https://github.com/ddelange/pipgrip/pull/67#issuecomment-942612902


> It also interesting to know which packages succeeded to be processes before the failure and which are not.

all succeeded ones (and there can only be one failed one) for the current best guess tree will be visualised -- for any other tree in the ensemble, I guess there is no trivial way of getting statistics on the solving process apart from analysing the logs...

**Comment by ddelange** [comment]
Release builds are triggered from the repo's releases tab (creating and releasing a new tag from there) - github actions (and setuptools_scm) takes care of the rest :)
